plan:
    package: ./2021/dagger/prod_image
name: prod_image
inputs:
    app_src:
        dir:
            path: .
            exclude:
                - .circleci
                - .dagger
                - .git
                - .github
                - "2021"
                - "2022"
                - _build/dev
                - _build/test
                - assets/node_modules
                - cue.mod
                - dev_docker
                - docker
                - import
                - nginx
                - priv/db
                - priv/uploads
                - script
                - tmp
                - .all-contributorsrc
                - .autocomplete
                - .credo.exs
                - .dockerignore
                - .formatter.exs
                - .envrc
                - .env
                - .gitattributes
                - .gitignore
                - README.md
                - coveralls.json
                - start_dev_stack.sh
                - .kube
                - erl_crash.dump
                - deps
                - _build
                - dagger
    app_version:
        text: 22.11.13+c84768a1d0df8afd6f8848d0100af252e85f6dc1
    build_url:
        text: https://github.com/thechangelog/changelog.com/actions
    build_version:
        text: 22.11.13+c84768a1d0df8afd6f8848d0100af252e85f6dc1
    docker_host:
        text: tcp://100.81.87.121:2375
    dockerhub_password:
        secret: ENC[AES256_GCM,data:ZaD/Ms4j+GVmmV8Bi8SpOLykYwM=,iv:H9VzVM/6aPQTECXSqO3YJVgcDSclsg1n0PEbeqjKZQQ=,tag:N6utU8mE7NUg8votw1aoLA==,type:str]
    dockerhub_username:
        text: changelogci
    git_author:
        text: gerhard
    git_sha:
        text: c84768a1d0df8afd6f8848d0100af252e85f6dc1
    prod_dockerfile:
        text: |
            FROM thechangelog/legacy_assets AS legacy_assets
            FROM thechangelog/runtime:2022-11-13T07.34.05Z

            RUN mkdir /app
            ARG APP_FROM_PATH=.
            COPY ${APP_FROM_PATH} /app
            WORKDIR /app
            RUN echo "Ensure deps are present & OK..." \
              ; ls -lahd deps/*
            RUN echo "Ensure prod bytecode is present & OK..." \
              ; ls -lahd _build/prod/lib/*/ebin
            RUN echo "Ensure prod static assets are present & OK..." \
              ; ls -lah priv/static/cache_manifest.json

            COPY --from=legacy_assets /var/www/wp-content /app/priv/wp-content

            ENV MIX_ENV=prod
            ENV TERM=xterm

            # Used by PromEx for annotations
            ARG GIT_AUTHOR
            ENV GIT_AUTHOR=${GIT_AUTHOR}
            ARG GIT_SHA
            ENV GIT_SHA=${GIT_SHA}
            ARG APP_VERSION
            ENV APP_VERSION=${APP_VERSION}

            ARG BUILD_URL
            ENV BUILD_URL=${BUILD_URL}
            # Used by various tooling to report the identity & origin of this build
            RUN echo "$GIT_SHA" > priv/static/version.txt \
              ; echo "$GIT_AUTHOR" > COMMIT_USER \
              ; echo "$BUILD_URL" > priv/static/build.txt

            EXPOSE 4000

            CMD make on-app-start; mix changelog.static.upload; mix do ecto.create, ecto.migrate, phx.server
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jl7vc68wfe2carr7qhe83r540fh8ayjensmym5p5ddsky84cvvas0gyr6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMUhQK2pFelNqbjh1cHVa
            OCs1T3AzT085SHlWV0MyMmNRWDlpZUxqSFRBCnhibDhoQUpaZVhpMTdJQjZTT2FO
            SEVqWkhzVXhuazZpTndYZm1wM1dNSGMKLS0tIGpIZHdob1YrbnVQbnNmbTg2cVNr
            ZE8xQlF0bHVZejFHeEwzZXBwZnF3encK8DzznyIRG/Hq9PDpF52XFE1phXd5Cwcu
            aphxZYpkm6JiBQySohnqHYCdN0xjCJOXOHAGIdnoog94rnRGqbqrew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T07:51:43Z"
    mac: ENC[AES256_GCM,data:4skxsEcznFxigZ2yLOtxAxxo5CRmiZwMxZxBJzy6Xe0QV9RKgGGLswEIXyYx1XE0H35D7BEm4qKX/eqCd6ZNCP6X1hGvqW4wR3jOPinCpxj5cTeYLtqvdPE3eYYP9WztLwpw/ndion9LjV+1Hdnes3fL9IPkMgpW9hOTe39PME4=,iv:agqCrcoIQUYpmdLRsPj6u8ZA/+GlNhyn4dR12+gcoyI=,tag:931vmINorFrYNjvXJHfOMg==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
