# Inspired by https://github.com/fly-apps/docker-daemon/blob/main/fly.toml
# https://fly.io/docs/reference/configuration/

app = "docker-2022-06-13"
kill_signal = "SIGINT"
kill_timeout = 30

[[mounts]]
  source = "data"
  destination = "/data"
